import { getAiConfigIssue } from "../aiProviders.js";
import { getMapById } from "../appData.js";
import { renderMapThumbnail } from "../components/mapThumbnail.js";
import { analyzeGlobalReview } from "../review/globalReviewApi.js";
import { activateQueueItem, completeReviewQueue, createGlobalReviewQueue, getActiveGlobalReviewQueue, getReviewQueueById, moveQueueItem, pauseReviewQueue, resumeReviewQueue, saveReviewQueue, setQueueItemStatus } from "../review/globalReviewStore.js";
import { createReviewState } from "../review/reviewState.js";
import { escapeHtml } from "../utils/jsonUtils.js";
import { setActiveMap } from "../state.js";

export function renderGlobalReviewWorkspacePage(state) {
  const queue = getReviewQueueById(state.appData, state.activeReviewQueueId) || getActiveGlobalReviewQueue(state.appData);
  if (!queue || queue.status === "draft" || queue.status === "analyzing") return renderInput(state, queue);
  if (queue.status === "completed") return renderCompleted(queue);
  return renderQueue(state, queue);
}

function renderInput(state, queue) { const raw = queue?.rawInput || ""; return `<main class="global-review-page"><header class="review-workspace-header"><div><p class="eyebrow">跨星图</p><h1>全局复盘</h1><p>用一段话总结今天的学习，AI 会先识别涉及哪些星图，再由你确定复盘顺序。</p></div><button data-global-review="back" type="button">返回复盘选择</button></header>${queue?.error ? `<section class="review-error"><strong>${escapeHtml(queue.error)}</strong>${queue.rawOutput ? `<details><summary>查看模型原始输出</summary><pre>${escapeHtml(queue.rawOutput)}</pre></details>` : ""}</section>` : ""}<section class="review-stage-card"><h2>总体学习总结</h2><textarea id="globalReviewInput" rows="10" placeholder="今天学了什么、做了什么、哪些地方顺利、哪些地方还不确定？">${escapeHtml(raw)}</textarea><div class="review-stage-actions"><button data-global-review="analyze" type="button" ${queue?.status === "analyzing" ? "disabled" : ""}>${queue?.status === "analyzing" ? "正在分析..." : "分析涉及的星图"}</button>${queue?.error ? `<button class="quiet-button" data-global-review="manual" type="button">手动选择星图</button>` : ""}</div></section></main>`; }

function renderQueue(state, queue) { const items = queue.items.slice().sort((a,b) => a.order - b.order); return `<main class="global-review-page"><header class="review-workspace-header"><div><p class="eyebrow">全局复盘队列</p><h1>选择复盘顺序</h1><p>${escapeHtml(queue.analysisSummary || "确认候选星图后，逐张进入现有单图复盘。")}</p></div><div class="queue-header-actions"><button data-global-review="pause" type="button">稍后继续</button><button data-global-review="finish" type="button">结束本次复盘</button></div></header>${queue.status === "paused" ? `<section class="queue-resume-notice">这次全局复盘已暂停。<button data-global-review="resume" type="button">继续全局复盘</button></section>` : ""}<section class="queue-layout"><section class="queue-list">${items.map((item) => renderQueueItem(state, queue, item)).join("") || `<p>尚未选择星图。</p>`}</section><aside class="unmatched-topics"><strong>未归档内容</strong>${(queue.unmatchedTopics || []).map((topic) => `<p>${escapeHtml(topic.title)}：${escapeHtml(topic.reason || "")}</p>`).join("") || "<p>没有未归档内容。</p>"}<label class="review-manual-node">手动补充星图<select id="globalManualMap"><option value="">选择星图</option>${state.appData.maps.filter((map) => !queue.items.some((item) => item.mapId === map.id)).map((map) => `<option value="${map.id}">${escapeHtml(map.title)}</option>`).join("")}</select></label><button data-global-review="add-manual" type="button">加入稍后处理</button></aside></section><div class="review-stage-actions"><button data-global-review="start-next" type="button" ${queue.status === "paused" ? "disabled" : ""}>开始处理优先星图</button></div></main>`; }

function renderQueueItem(state, queue, item) {
  const map = getMapById(state.appData, item.mapId);
  const invalid = !map;
  const standardActions = `
    <button data-queue-action="priority" data-item-id="${item.id}" type="button">优先</button>
    <button data-queue-action="deferred" data-item-id="${item.id}" type="button">稍后</button>
    <button data-queue-action="ignored" data-item-id="${item.id}" type="button">忽略</button>
    ${item.status === "ignored" ? `<button data-queue-action="restore" data-item-id="${item.id}" type="button">恢复</button>` : ""}
    ${item.status === "priority" ? `<button data-queue-action="up" data-item-id="${item.id}" type="button">↑</button><button data-queue-action="down" data-item-id="${item.id}" type="button">↓</button>` : ""}
    ${item.status === "completed" ? `<button data-queue-action="view" data-item-id="${item.id}" type="button">查看地图</button>` : ""}
  `;
  return `<article class="queue-card queue-${invalid ? "invalid" : item.status}"><div class="queue-thumbnail">${map ? renderMapThumbnail(map) : "星图已不存在"}</div><div><p class="eyebrow">${label(item.status)}</p><h3>${escapeHtml(item.mapTitle)}</h3><p>${escapeHtml(item.reason || item.extractedSummary || "")}</p><small>置信度 ${Math.round((Number(item.confidence) || 0) * 100)}%</small>${item.status === "completed" ? `<p class="queue-result">${escapeHtml(item.resultSummary?.recordSummary || "已完成本次复盘")}</p>` : ""}<div class="queue-item-actions">${invalid ? `<button data-queue-action="remove" data-item-id="${item.id}" type="button">移除</button>` : standardActions}</div></div></article>`;
}
function label(status) { return ({priority:"优先复盘",deferred:"稍后处理",ignored:"本次忽略",active:"正在复盘",completed:"已完成",invalid:"星图已不存在"})[status] || status; }
function renderCompleted(queue) { const done = queue.items.filter((item) => item.status === "completed"); const updated = done.reduce((sum,item) => sum + (item.resultSummary?.masteryUpdates || 0), 0); return `<main class="global-review-page"><section class="review-stage-card global-complete"><p class="eyebrow">全局复盘</p><h1>本次全局复盘完成</h1><p>${escapeHtml(queue.analysisSummary)}</p><dl class="map-metadata"><div><dt>已分析星图</dt><dd>${queue.items.length}</dd></div><div><dt>已完成</dt><dd>${done.length}</dd></div><div><dt>更新节点</dt><dd>${updated}</dd></div><div><dt>已搁置</dt><dd>${queue.items.filter((item) => item.status === "deferred").length}</dd></div></dl><button data-global-review="back" type="button">返回复盘选择</button></section></main>`; }

export function bindGlobalReviewWorkspacePageEvents(state, renderApp) {
  document.querySelectorAll("[data-global-review]").forEach((button) => button.addEventListener("click", async () => { const action = button.dataset.globalReview; let queue = getReviewQueueById(state.appData, state.activeReviewQueueId) || getActiveGlobalReviewQueue(state.appData); if (action === "back") { state.currentMode = "review"; state.currentPage = "map_selection_review"; renderApp(); return; } if (action === "analyze") { const raw = document.querySelector("#globalReviewInput")?.value.trim() || ""; if (!raw) return; await analyzeQueue(state, queue, raw, renderApp); return; } if (action === "manual") { if (!queue) { queue = createGlobalReviewQueue(""); queue.status = "selecting"; saveReviewQueue(state.appData, queue); state.activeReviewQueueId = queue.id; } renderApp(); return; } if (!queue) return; if (action === "pause") { pauseReviewQueue(state.appData, queue.id); state.currentMode = "review"; state.currentPage = "map_selection_review"; renderApp(); return; } if (action === "resume") { resumeReviewQueue(state.appData, queue.id); renderApp(); return; } if (action === "add-manual") { const mapId = document.querySelector("#globalManualMap")?.value; const map = getMapById(state.appData, mapId); if (map) { queue.items.push(makeItem(map, queue.items.length + 1, "deferred", { reason: "用户手动补充" })); saveReviewQueue(state.appData, queue); } renderApp(); return; } if (action === "start-next") { startItem(state, queue, "", renderApp); return; } if (action === "finish") { const priority = queue.items.filter((item) => item.status === "priority"); if (priority.length && !window.confirm("还有优先复盘的星图未完成。仍然结束并将其设为稍后处理吗？")) return; priority.forEach((item) => { item.status = "deferred"; }); completeReviewQueue(state.appData, queue.id); renderApp(); } })); document.querySelectorAll("[data-queue-action]").forEach((button) => button.addEventListener("click", () => { const queue = getReviewQueueById(state.appData, state.activeReviewQueueId) || getActiveGlobalReviewQueue(state.appData); if (!queue) return; const action = button.dataset.queueAction; const item = queue.items.find((entry) => entry.id === button.dataset.itemId); if (!item) return; if (action === "up" || action === "down") moveQueueItem(state.appData, queue.id, item.id, action === "up" ? -1 : 1); else if (action === "remove") { queue.items = queue.items.filter((entry) => entry.id !== item.id); saveReviewQueue(state.appData, queue); } else if (action === "view") { setActiveMap(item.mapId); const feedback = queue.feedbacks?.find((entry) => entry.mapId === item.mapId); if (feedback) state.pendingMapFeedback = feedback; state.currentMode = "review"; state.mapEntryContext = { sourceView: "map_selection_review", mode: "review" }; state.currentPage = "map"; } else setQueueItemStatus(state.appData, queue.id, item.id, action === "restore" ? "deferred" : action); renderApp(); })); }

async function analyzeQueue(state, currentQueue, rawInput, renderApp) { const issue = getAiConfigIssue(state.aiConfig); let queue = currentQueue || createGlobalReviewQueue(rawInput); if (!currentQueue) { state.appData.reviewQueues.unshift(queue); state.activeReviewQueueId = queue.id; } queue.rawInput = rawInput; queue.status = "analyzing"; queue.error = ""; saveReviewQueue(state.appData, queue); if (issue) { queue.status = "draft"; queue.error = issue; saveReviewQueue(state.appData, queue); renderApp(); return; } renderApp(); try { const result = await analyzeGlobalReview(rawInput, state.appData.maps, state.appData.learningRecords, state.aiConfig); queue.analysisSummary = result.summary; queue.unmatchedTopics = result.unmatchedTopics; queue.items = result.candidateMaps.map((candidate, index) => { const map = getMapById(state.appData, candidate.mapId); return map ? makeItem(map, index + 1, "priority", candidate) : null; }).filter(Boolean); queue.status = "selecting"; queue.rawOutput = ""; } catch (error) { queue.status = "draft"; queue.error = error.message; queue.rawOutput = error.message; } saveReviewQueue(state.appData, queue); renderApp(); }
function makeItem(map, order, status, candidate = {}) { return { id: `queue-item-${Date.now().toString(36)}-${order}`, mapId: map.id, mapTitle: map.title, status, order, confidence: Number(candidate.confidence) || 0, reason: candidate.reason || "", matchedTopics: candidate.matchedTopics || [], extractedSummary: candidate.extractedSummary || "", extractedEvidence: candidate.extractedEvidence || [], reviewRecordId: null, reviewSessionId: null, completedAt: null, resultSummary: null }; }
function startItem(state, queue, itemId, renderApp) { const activated = activateQueueItem(state.appData, queue.id, itemId); if (!activated) { renderApp(); return; } state.activeReviewQueueId = queue.id; state.activeReviewItemMapId = activated.item.mapId; setActiveMap(activated.item.mapId); state.review = { ...createReviewState(), ...(activated.item.reviewDraft || {}) }; state.review.entryContext = { entryType: "global_review_item", sourceQueueId: queue.id, sourceQueueItemId: activated.item.id, prefilledSummary: activated.item.extractedSummary, prefilledTopics: activated.item.matchedTopics, prefilledEvidence: activated.item.extractedEvidence, globalRawInput: queue.rawInput }; if (!state.review.rawInput) state.review.rawInput = [activated.item.extractedSummary, queue.rawInput].filter(Boolean).join("\n\n"); state.currentMode = "review"; state.currentPage = "review_workspace"; renderApp(); }
